---
- name: "Setup workstation for personal/school use"
  hosts: all
  become: yes
  tasks:
    - name: "Update existing pacman packages"
      pacman:
        update_cache: true
        upgrade: true
    - name: "Ensure pacman packages are installed"
      pacman:
        update_cache: true
        name:
          - flatpak
          - base
          - base-devel
          - git
          - vim
          - neofetch
          - lolcat 
          - plasma-meta
          - zsh
          - zsh-completions
          - ntp
          - ark
          - okular
          - dolphin
        state: latest
    - name: "Ensure flatpak applications are installed"
      flatpak:
        name:
          - org.mozilla.firefox
          - org.texstudio.TeXstudio
          - com.microsoft.Teams
          - com.github.micahflee.torbrowser-launcher
          - org.geogebra.GeoGebra
          - com.jgraph.drawio.desktop
          - md.obsidian.Obsidian
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
          - org.telegram.desktop
          - com.spotify.Client
          - com.discordapp.Discord
          - net.ankiweb.Anki
          - com.nextcloud.desktopclient.nextcloud
          - org.keepassxc.KeePassXC
            # application might be broken - doesn't work manually either
            #- com.jetbrains.IntelliJ-IDEA-Ultimate
          - com.github.xournalpp.xournalpp
        state: present
    - name: "Ensure services are enabled and started"
      service:
        name: ntpd
        state: started
        enabled: yes
    - name: "Ensure timezone and hwclock are set correctly"
      timezone:
        name: "Europe/Vienna"
        hwclock: "UTC"

# begin: source=https://serverfault.com/questions/959026/how-do-i-generate-and-set-the-locale-using-ansible, 2022-11-02 (edited)
    - name: "Ensure localisation files for 'de_AT.UTF-8' are available"
      locale_gen:
        name: "de_AT.UTF-8"
        state: present

    - name: "Ensure localisation files for 'en_US.UTF-8' are available"
      locale_gen:
        name: "en_US.UTF-8"
        state: present

    - name: "Ensure localisation files for 'en_DK.UTF-8' are available"
      locale_gen:
        name: "en_DK.UTF-8"
        state: present

    - name: "Get current locale and language configuration"
      command: "localectl status"
      register: locale_status
      changed_when: false

    - name: "Parse 'LANG' from current locale and language configuration"
      set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

    - name: "Parse 'LANGUAGE' from current locale and language configuration"
      set_fact:
        locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

    - name: "Configure locale to 'de_AT.UTF-8' and language to 'en_US.UTF-8'"
      command: "localectl set-locale LANG=de_AT.UTF-8 LANGUAGE=en_US.UTF-8"
      changed_when: locale_lang != "de_AT.UTF-8" or locale_language != "en_US.UTF-8"
# end: source=https://serverfault.com/questions/959026/how-do-i-generate-and-set-the-locale-using-ansible, 2022-11-02 (edited)

    - name: "Parse 'VC Keymap' from current locale and language configuration"
      set_fact:
        vc_keymap: "{{ locale_status.stdout | regex_search('VC Keymap: ([^\n]+)', '\\1') | first }}"

    - name: "Configure 'VC Keymap' to 'de-latin1-nodeadkeys'"
      command: "localectl set-keymap de-latin1-nodeadkeys"
      changed_when: vc_keymap != "de-latin1-nodeadkeys"

    # source for ISO8601: https://wiki.archlinux.org/title/Locale#LC_TIME:_date_and_time_format
    - name: "Ensure time format is set to ISO8601"
      lineinfile:
        path: /etc/locale.conf
        regexp: "LC_TIME=(^\\n)"
        line: "LC_TIME=en_DK.UTF-8"
        backup: true
