---
- name: Install programs
  hosts: all
  become: yes
  tasks:
    - name: Install flatpak
      pacman:
        name: flatpak
        state: present
    - name: Install flatpaks
      flatpak:
        name: Install firefox
          - org.mozilla.firefox
          - com.microsoft.Teams
          - com.github.micahflee.torbrowser-launcher
          - md.obsidian.Obsidian
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
          - org.telegram.desktop
          - com.spotify.Client
          - com.discordapp.Discord
        state: present

